//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEncuestas.Utilidades.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaEncuestas.Utilidades.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento un Error al Cargar los datos del objeto..
        /// </summary>
        public static string ErrorCargarDatos {
            get {
                return ResourceManager.GetString("ErrorCargarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{&apos;visa&apos;: &apos;{0}&apos;, &apos;master&apos;: &apos;{1}&apos;, &apos;diners&apos;: &apos;{2}&apos;, &apos;american&apos;: &apos;{3}&apos;, &apos;discover&apos;: &apos;{4}&apos;}}.
        /// </summary>
        public static string JSONMensajesFranquicia {
            get {
                return ResourceManager.GetString("JSONMensajesFranquicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa|Master Card|American Express|Diners Club|Discover.
        /// </summary>
        public static string ListaFranquicias {
            get {
                return ResourceManager.GetString("ListaFranquicias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre.
        /// </summary>
        public static string ListaMeses {
            get {
                return ResourceManager.GetString("ListaMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Afganistan&quot;, 
        ///&quot;Albania&quot;, 
        ///&quot;Alemania&quot;, 
        ///&quot;Andorra&quot;, 
        ///&quot;Angola&quot;, 
        ///&quot;Antartida&quot;, 
        ///&quot;Antigua y Barbuda&quot;, 
        ///&quot;Arabia Saudi&quot;, 
        ///&quot;Argelia&quot;, 
        ///&quot;Argentina&quot;, 
        ///&quot;Armenia&quot;, 
        ///&quot;Australia&quot;, 
        ///&quot;Austria&quot;, 
        ///&quot;Azerbaiyan&quot;, 
        ///&quot;Bahamas&quot;, 
        ///&quot;Bahrain&quot;, 
        ///&quot;Bangladesh&quot;, 
        ///&quot;Barbados&quot;, 
        ///&quot;Belgica&quot;, 
        ///&quot;Belice&quot;, 
        ///&quot;Benin&quot;, 
        ///&quot;Bermudas&quot;, 
        ///&quot;Bielorrusia&quot;, 
        ///&quot;Birmania Myanmar&quot;, 
        ///&quot;Bolivia&quot;, 
        ///&quot;Bosnia y Herzegovina&quot;, 
        ///&quot;Botswana&quot;, 
        ///&quot;Brasil&quot;, 
        ///&quot;Brunei&quot;, 
        ///&quot;Bulgaria&quot;, 
        ///&quot;Burkina Faso&quot;, 
        ///&quot;Burundi&quot;, 
        ///&quot;Butan&quot;, 
        ///&quot;Cabo Verde&quot;, 
        ///&quot;Camboya [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ListaPaises {
            get {
                return ResourceManager.GetString("ListaPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito.
        /// </summary>
        public static string ListaTipoTarjeta {
            get {
                return ResourceManager.GetString("ListaTipoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción de la auditoría de forma correcta..
        /// </summary>
        public static string MensajeAuditoriaIngresoSuccess {
            get {
                return ResourceManager.GetString("MensajeAuditoriaIngresoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontró el registro {0}..
        /// </summary>
        public static string MensajeBusquedaEntidadSuccess {
            get {
                return ResourceManager.GetString("MensajeBusquedaEntidadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro solicitado..
        /// </summary>
        public static string MensajeBusquedaEntidadWarning {
            get {
                return ResourceManager.GetString("MensajeBusquedaEntidadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo destinado ha sido enviado..
        /// </summary>
        public static string MensajeCorreoEnviado {
            get {
                return ResourceManager.GetString("MensajeCorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no ha podido ser enviado..
        /// </summary>
        public static string MensajeCorreoError {
            get {
                return ResourceManager.GetString("MensajeCorreoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se relizó la inserción de la empresa de forma correcta..
        /// </summary>
        public static string MensajeEmpresaSuccess {
            get {
                return ResourceManager.GetString("MensajeEmpresaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción de la encuesta de forma correcta..
        /// </summary>
        public static string MensajeEncuestaSuccess {
            get {
                return ResourceManager.GetString("MensajeEncuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar la encuesta..
        /// </summary>
        public static string MensajeErrorEncuesta {
            get {
                return ResourceManager.GetString("MensajeErrorEncuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar una opción de una pregunta de la encuesta..
        /// </summary>
        public static string MensajeErrorOpcion {
            get {
                return ResourceManager.GetString("MensajeErrorOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al guardar una pregunta de la encuesta..
        /// </summary>
        public static string MensajeErrorPregunta {
            get {
                return ResourceManager.GetString("MensajeErrorPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del ítem del plan de forma correcta..
        /// </summary>
        public static string MensajeItemPlanSuccess {
            get {
                return ResourceManager.GetString("MensajeItemPlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del ítem de la pregunta de forma correcta.
        /// </summary>
        public static string MensajeItemPreguntaSuccess {
            get {
                return ResourceManager.GetString("MensajeItemPreguntaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron {0} registros..
        /// </summary>
        public static string MensajeListaSuccess {
            get {
                return ResourceManager.GetString("MensajeListaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros..
        /// </summary>
        public static string MensajeListaWarning {
            get {
                return ResourceManager.GetString("MensajeListaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado no coincide con la contraseña o no existe..
        /// </summary>
        public static string MensajeLoginError {
            get {
                return ResourceManager.GetString("MensajeLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso exitoso.
        /// </summary>
        public static string MensajeLoginSuccess {
            get {
                return ResourceManager.GetString("MensajeLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del control de forma correcta..
        /// </summary>
        public static string MensajeMetadataSuccess {
            get {
                return ResourceManager.GetString("MensajeMetadataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del pago de forma correcta..
        /// </summary>
        public static string MensajePagoPlanSuccess {
            get {
                return ResourceManager.GetString("MensajePagoPlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El párametro se encuentra nulo..
        /// </summary>
        public static string MensajeParametroWarning {
            get {
                return ResourceManager.GetString("MensajeParametroWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del plan de la empresa de forma correcta..
        /// </summary>
        public static string MensajePlanEmpresaSuccess {
            get {
                return ResourceManager.GetString("MensajePlanEmpresaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del plan de forma correcta..
        /// </summary>
        public static string MensajePlanSuccess {
            get {
                return ResourceManager.GetString("MensajePlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del precio de forma correcta..
        /// </summary>
        public static string MensajePrecioSuccess {
            get {
                return ResourceManager.GetString("MensajePrecioSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción de la pregunta de forma correcta..
        /// </summary>
        public static string MensajePreguntaSuccess {
            get {
                return ResourceManager.GetString("MensajePreguntaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento un error en la insercion de la respuesta.
        /// </summary>
        public static string MensajeRespuestaFail {
            get {
                return ResourceManager.GetString("MensajeRespuestaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción de la respuesta de forma correcta.
        /// </summary>
        public static string MensajeRespuestaSuccess {
            get {
                return ResourceManager.GetString("MensajeRespuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del rol de forma correcta..
        /// </summary>
        public static string MensajeRolSuccess {
            get {
                return ResourceManager.GetString("MensajeRolSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la inserción del usuario de forma correcta..
        /// </summary>
        public static string MensajeUsuarioSuccess {
            get {
                return ResourceManager.GetString("MensajeUsuarioSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Presento Un Error Al eliminar la Encuesta.
        /// </summary>
        public static string MessageDeleteEncuestaFailed {
            get {
                return ResourceManager.GetString("MessageDeleteEncuestaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La encuesta se ha eliminado Correctamente..
        /// </summary>
        public static string MessageDeleteEncuestaSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteEncuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidacionErrorTarjetaAmerican.
        /// </summary>
        public static string nombreRecursoAE {
            get {
                return ResourceManager.GetString("nombreRecursoAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidacionErrorTarjetaDiscover.
        /// </summary>
        public static string nombreRecursoDC {
            get {
                return ResourceManager.GetString("nombreRecursoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidacionErrorTarjetaDiners.
        /// </summary>
        public static string nombreRecursoDI {
            get {
                return ResourceManager.GetString("nombreRecursoDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidacionErrorTarjetaMaster.
        /// </summary>
        public static string nombreRecursoMC {
            get {
                return ResourceManager.GetString("nombreRecursoMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidacionErrorTarjetaVisa.
        /// </summary>
        public static string nombreRecursoVI {
            get {
                return ResourceManager.GetString("nombreRecursoVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tarjetas American Express comienzan con el número 3 y contienen 15 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaAmerican {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tarjetas Diners pueden comenzar por los números 3 o 6 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaDiners {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaDiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tarjetas Discover pueden comenzar por los números 3 o 6 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaDiscover {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tarjetas Master Card comienzan por el número 2 o 5 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaMaster {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tarjetas Visa comienzan por el número 4 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaVisa {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaVisa", resourceCulture);
            }
        }
    }
}
